package cn.nubia.gamelauncher.commoninterface;

import android.net.Uri;
import java.util.ArrayList;
import java.util.HashMap;

public class ConstantVariable {
    public static Uri APPADD_URI = Uri.parse("content://cn.nubia.gamelauncher.db.AppAddProvider/appadd?notify=true");
    public static Uri APPADD_URI_NO_NOTIFY = Uri.parse("content://cn.nubia.gamelauncher.db.AppAddProvider/appadd?notify=false");
    public static int APP_TYPE_GAME = 2;
    public static int APP_TYPE_NORMAL_APP = 1;
    public static boolean HAS_PERMISSION = false;
    public static HashMap<String, String> LOCAL_GAME_IMAGE_MAP = new HashMap<>();
    public static final Uri NEOExtendDB_URI = Uri.parse("content://cn.nubia.launcher.extend/neostore_download");
    public static final String NEOICONDOWNLOAD_TABLE = "neostore_download";
    public static final String NEO_AUTHORITY = "cn.nubia.launcher.extend";
    public static int STATE_CODE_SUCESS = 1;
    public static ArrayList<String> SYSTEM_APP_LIST = new ArrayList<>();
    public static final int TYPE_ADD = 0;
    public static final int TYPE_UNINSTALL = 1;
    public static Uri USER_ROMOVE_URI = Uri.parse("content://cn.nubia.gamelauncher.db.AppAddProvider/user_remove?notify=true");
    public static Uri USER_ROMOVE_URI_NO_NOTIFY = Uri.parse("content://cn.nubia.gamelauncher.db.AppAddProvider/user_remove?notify=false");

    static {
        SYSTEM_APP_LIST.add("cn.nubia.neogamecenter");
        SYSTEM_APP_LIST.add("cn.nubia.browser");
        SYSTEM_APP_LIST.add("cn.nubia.calendar.preset");
        SYSTEM_APP_LIST.add("cn.nubia.contacts");
        SYSTEM_APP_LIST.add("cn.nubia.deskclock.preset");
        SYSTEM_APP_LIST.add("cn.nubia.gallery3d");
        SYSTEM_APP_LIST.add("cn.nubia.mms");
        SYSTEM_APP_LIST.add("com.android.camera");
        SYSTEM_APP_LIST.add("com.android.settings");
        SYSTEM_APP_LIST.add("cn.nubia.music.preset");
        SYSTEM_APP_LIST.add("cn.nubia.neostore");
        SYSTEM_APP_LIST.add("cn.nubia.neoshare");
        SYSTEM_APP_LIST.add("cn.nubia.thememanager");
        SYSTEM_APP_LIST.add("cn.nubia.security2");
        SYSTEM_APP_LIST.add("cn.nubia.weather");
        SYSTEM_APP_LIST.add("cn.nubia.myfile");
        SYSTEM_APP_LIST.add("cn.nubia.flycow");
        SYSTEM_APP_LIST.add("com.chaozh.iReaderNubia");
        SYSTEM_APP_LIST.add("cn.nubia.bbs");
        SYSTEM_APP_LIST.add("cn.nubia.nubiashop");
        SYSTEM_APP_LIST.add("cn.nubia.notepad.preset");
        SYSTEM_APP_LIST.add("cn.nubia.calculator2.preset");
        SYSTEM_APP_LIST.add("cn.nubia.soundrecorder.preset");
        SYSTEM_APP_LIST.add("cn.nubia.wfd");
        SYSTEM_APP_LIST.add("cn.nubia.gamelauncher");
        SYSTEM_APP_LIST.add("cn.nubia.launcher");
        SYSTEM_APP_LIST.add("cn.nubia.v5light.preset");
        SYSTEM_APP_LIST.add("com.redteamobile.roaming");
        SYSTEM_APP_LIST.add("cm.nubia.wallet");
        SYSTEM_APP_LIST.add("com.kookong.app.nubia");
        SYSTEM_APP_LIST.add("cn.nubia.lighteditor");
        SYSTEM_APP_LIST.add("cn.nubia.voiceassist");
        SYSTEM_APP_LIST.add("cn.nubia.eyesprotection");
        SYSTEM_APP_LIST.add("cn.nubia.smartscanner");
        SYSTEM_APP_LIST.add("cn.nubia.touping");
        SYSTEM_APP_LIST.add("com.android.chrome");
        SYSTEM_APP_LIST.add("com.google.android.apps.tachyon");
        SYSTEM_APP_LIST.add("com.google.android.googlequicksearchbox");
        SYSTEM_APP_LIST.add("com.google.android.apps.maps");
        SYSTEM_APP_LIST.add("org.codeaurora.dialer");
        SYSTEM_APP_LIST.add("com.android.mms");
        SYSTEM_APP_LIST.add("com.android.calculator2");
        SYSTEM_APP_LIST.add("com.google.android.calendar");
        SYSTEM_APP_LIST.add("com.android.deskclock");
        SYSTEM_APP_LIST.add("com.android.contacts");
        SYSTEM_APP_LIST.add("com.android.documentsui");
        SYSTEM_APP_LIST.add("com.google.android.googlequicksearchbox");
        SYSTEM_APP_LIST.add("com.google.android.apps.docs");
        SYSTEM_APP_LIST.add("com.google.android.apps.photos");
        SYSTEM_APP_LIST.add("com.silead.frrfar");
        SYSTEM_APP_LIST.add("com.google.android.gm");
        SYSTEM_APP_LIST.add("com.android.vending");
        SYSTEM_APP_LIST.add("com.google.android.music");
        SYSTEM_APP_LIST.add("com.google.android.videos");
        SYSTEM_APP_LIST.add("com.google.android.youtube");
        SYSTEM_APP_LIST.add("com.google.android.apps.messaging");
        SYSTEM_APP_LIST.add("com.nubia.usermanual");
        SYSTEM_APP_LIST.add("com.nubia.neogamecenter");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.gwgo", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.mrzh.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.mrzh.aligames", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.mrzh", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wxzc", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wxzc.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wxzc.aligames", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.lzhx", "");
        LOCAL_GAME_IMAGE_MAP.put("com.superevilmegacorp.game.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.yingxiong.dfzj.hero", "");
        LOCAL_GAME_IMAGE_MAP.put("com.yingxiong.dftk.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.fctw", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.af", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.moba", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.moba.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.kaopu.jzpaj", "");
        LOCAL_GAME_IMAGE_MAP.put("com.aligames.kuang.kybc.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.aligames.kuang.kybc", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.jxqy", "jianxiaqingyuan.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.crossgate", "molibaobei.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.sofunny.Sausage", "xiangchangpaidui.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.blizzard.wtcg.hearthstone", "luoshichuanshuo.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.WePop", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ilongyuan.autochess.ly_pre", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.lztg", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.lztg.nubia", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.lztg.huawei", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.lztg.aligames", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmpg.yongyong.lztg", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.sgame", "sgame.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.sgamece", "sgame.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.hyxd.nubia", "wilderness_war.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.hyxd.aligames", "wilderness_war.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.hyxd", "wilderness_war.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.speedmobile", "qq_speed_car.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.happyelements.AndroidAnimal", "happy.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.pubgmhd", "pubgmhd.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.cf", "cf.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.zjz.nubia", "terminator.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.zjz", "terminator.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.pubgm", "pubgm.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.shootgame", "shootgame.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.miHoYo.bh3.uc", "bh3.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wyclx.nubia", "clx.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wyclx", "clx.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.dwrg.nubia", "five.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.dwrg", "five.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.dwrg.aligames", "five.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.idv.googleplay", "five.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.lx12.nubia", "shoot_star.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.lx12", "shoot_star.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.cmge.ssjd.nubia", "ssjd.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.cmge.ssjd", "ssjd.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.ffom", "ffom.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.joym.legendhero.nubia", "aotumen_hero.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.joym.legendhero", "aotumen_hero.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.yaowan.dfh3.nubia", "big_rich_men.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.yaowan.dfh3", "big_rich_men.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.dhxy", "dahuaxiyou.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.jiguang.dtszj.nubia", "dtszj.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.jiguang.dtszj", "dtszj.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.playcrab.dazhangmen2.nubia", "dzm2.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.playcrab.dazhangmen2", "dzm2.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.kiloo.subwaysurf", "subwaysurf.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.mars.fkdqq.nubia", "fkdqq.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.mars.fkdqq", "fkdqq.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.yodo1.rodeo.YODO1", "YODO1.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.yodo1.ctr2.DSYD_01", "ctr2.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.moli.minigame.hole.nubia", "minigame.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.moli.minigame.hole", "minigame.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.sgw.hlbyr.nubia", "hlbyr.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.sgw.hlbyr", "hlbyr.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.anzhuojpzmg.ckhd.nubia", "anzhuojpzmg.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.anzhuojpzmg.ckhd", "anzhuojpzmg.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.stzb.nubia", "stzb.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.stzb", "stzb.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.ledou.mhhy", "mhhy.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.ledou.mhjy.nubia", "mhjy.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.ledou.mhjy", "mhjy.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.my", "my.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.simcitymobile.nubia", "simcitymobile.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.simcitymobile", "simcitymobile.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.legu.homm.nubia", "homm.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.legu.homm", "homm.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.bf.sgs.hdexp.nubia", "sgs.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.bf.sgs.hdexp", "sgs.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.imangi.templerun2", "templerun2.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wdsj.yyxx.nubia", "wdsj.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.wdsj.yyxx", "wdsj.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.leqi.buyu.nubia", "leqi_buyu.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.leqi.buyu", "leqi_buyu.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.onmyoji", "onmyoji.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.zmq.nubia", "zmq.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.zmq", "zmq.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.popcap.pvz2cthdnby", "pvz2cthdnby.jpg");
        LOCAL_GAME_IMAGE_MAP.put("com.studiowildcard.wardrumstudios.ark", "");
        LOCAL_GAME_IMAGE_MAP.put("com.studiowildcard.wardrumstudios.ark.ncr", "");
        LOCAL_GAME_IMAGE_MAP.put("com.hypergryph.arknights", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netmarble.mherosgb", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.mff", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftA9HM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftA8HM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.kgtw", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.kgsam", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ngame.allstar.eu", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.ngame.chty", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.kgid", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.kgvn", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.kgvntest", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.kgth", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netmarble.penta", "");
        LOCAL_GAME_IMAGE_MAP.put("com.epicgames.fortnite", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.ig", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.iglite", "");
        LOCAL_GAME_IMAGE_MAP.put("com.pubg.krmobile", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.idv.googleplay", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.chiji", "");
        LOCAL_GAME_IMAGE_MAP.put("com.miHoYo.bh3rdJP", "");
        LOCAL_GAME_IMAGE_MAP.put("com.miHoYo.bh3oversea", "");
        LOCAL_GAME_IMAGE_MAP.put("com.miHoYo.bh3tw", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.bh3", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.ko", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.rs", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.cfmnac", "");
        LOCAL_GAME_IMAGE_MAP.put("com.stove.cfm.google", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.hyxdtw", "");
        LOCAL_GAME_IMAGE_MAP.put("com.squareenixmontreal.hitmansniperandroid", "");
        LOCAL_GAME_IMAGE_MAP.put("com.fungames.sniper3d", "");
        LOCAL_GAME_IMAGE_MAP.put("com.nianticlabs.pokemongo", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.idv_tw.googleplay", "");
        LOCAL_GAME_IMAGE_MAP.put("com.t2ksports.nba2k17and", "");
        LOCAL_GAME_IMAGE_MAP.put("com.t2ksports.nba2k18and", "");
        LOCAL_GAME_IMAGE_MAP.put("com.t2ksports.nba2k19and", "");
        LOCAL_GAME_IMAGE_MAP.put("com.t2ksports.nba2k20and", "");
        LOCAL_GAME_IMAGE_MAP.put("com.mobile.legends", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gm99.qh", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftASHM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.punch.realfist.boxingfightinggame", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ubisoft.assassinscreed.identity", "");
        LOCAL_GAME_IMAGE_MAP.put("com.Zonmob.Stickman.FightingGames.ShadowOfDeath", "");
        LOCAL_GAME_IMAGE_MAP.put("com.bandainamcogames.dbzdokkanww", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rockstargames.gtasa", "");
        LOCAL_GAME_IMAGE_MAP.put("com.garena.game.hdltw", "");
        LOCAL_GAME_IMAGE_MAP.put("com.minitech.miniworld", "");
        LOCAL_GAME_IMAGE_MAP.put("com.airfightwar.thunderbattle", "");
        LOCAL_GAME_IMAGE_MAP.put("com.h8games.helixjump", "");
        LOCAL_GAME_IMAGE_MAP.put("com.dts.freefireth", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ChillyRoom.DungeonShooter", "");
        LOCAL_GAME_IMAGE_MAP.put("com.xchange.JumpBall", "");
        LOCAL_GAME_IMAGE_MAP.put("com.supercell.clashofclans", "");
        LOCAL_GAME_IMAGE_MAP.put("com.supercell.clashroyale", "");
        LOCAL_GAME_IMAGE_MAP.put("jp.konami.pesam", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.gp.fifamobile", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftA9HM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftA8HM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.game.simcitymobile_row", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.gp.nbamobile", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rovio.baba", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rovio.angrybirds", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rovio.angrybirdsspaceHD", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rovio.angrybirdsstarwars.ads.iap", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rovio.angrybirdsstarwarsii.ads", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rovio.gold", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftM5HM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.game.pvzfree_row", "");
        LOCAL_GAME_IMAGE_MAP.put("com.igg.android.lordsmobile", "");
        LOCAL_GAME_IMAGE_MAP.put("com.racergame.cityracing3dck", "");
        LOCAL_GAME_IMAGE_MAP.put("com.bitmango.rolltheballunrollme", "");
        LOCAL_GAME_IMAGE_MAP.put("com.king.candycrushsaga", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.games.r3_row", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftZSHM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.gameloft.android.ANMP.GloftDMHM", "");
        LOCAL_GAME_IMAGE_MAP.put("com.more.dayzsurvival.gp", "");
        LOCAL_GAME_IMAGE_MAP.put("com.rsg.heroesevolved", "");
        LOCAL_GAME_IMAGE_MAP.put("com.archbears.bs", "");
        LOCAL_GAME_IMAGE_MAP.put("com.netease.g78na.tw", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.game.nfs14_row", "");
        LOCAL_GAME_IMAGE_MAP.put("com.sofunny.Chicken", "");
        LOCAL_GAME_IMAGE_MAP.put("com.milux.rolltheball", "");
        LOCAL_GAME_IMAGE_MAP.put("com.wikia.singlewikia.clashofclans", "");
        LOCAL_GAME_IMAGE_MAP.put("com.wikia.singlewikia.angrybirds", "");
        LOCAL_GAME_IMAGE_MAP.put("com.tencent.tmgp.supercell.clashroyale", "");
        LOCAL_GAME_IMAGE_MAP.put("com.ea.games.nfs13_na", "");
    }
}
